# Generated by Django 4.0.3 on 2022-03-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        choices=[("SUMMER", "Summer"), ("WINTER", "Winter"), ("SPRING", "Spring"), ("FALL", "Fall")],
                        db_index=True,
                        max_length=8,
                        unique=True,
                        verbose_name="Title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "default_related_name": "seasons",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Type")),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                ("image", models.URLField(max_length=250, verbose_name="Image Link")),
                ("season", models.ManyToManyField(related_name="item_season", to="app.season", verbose_name="Season")),
                (
                    "type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.type", verbose_name="Тип"),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
    ]
